id: A2445076B
title: A Prayer
type: translation
pechas:
- IE5AAACCE
- ICE740ACB
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:46:33.558755
  last_modified_at: 2023-01-04 11:46:33.558762
  collections:
  - Dudjom Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  IE5AAACCE/942C: '8304'
  ICE740ACB/D88D: '8304'
